### ISSUE TITLE
Dist directory missing

### ISSUE THREAD

**Issue by hollg** [semmiverian/react-form-validation#8]
Hi!

When I install the package from npm/yarn, the `dist` directory is missing.

It looks like build command hasn't been run before it was pushed to npm.

**Comment by semmiverian** [comment]
Hi @garyhollandxyz  thanks for reporting the issue , 
yes I think that's because I put the dist folder at .gitignore and because of that the dist folder is not being publish to the NPM 😓.

I update the .gitignore and published the new version that include the dist folder.

would you mind to update the library version and check if the dist folder already there.

thanks bro

**Comment by hollg** [comment]
@semmiverian thanks so much for the quick response and fix.

I've updated to the latest version and it works great!
